apiVersion: batch/v1
kind: Job
metadata:
  name: diag-codes-classifier
  labels:
    app: diag-codes-classifier
spec:
  template:
    metadata:
      labels:
        app: diag-codes-classifier
    spec:
      containers:
        - name: clinical-classification
          image: <anonymized>
          command: [
              "python", "classification_main.py",
              "fit",
              "--trainer.accelerator=gpu",
              "--trainer.devices=1",
              "--trainer.precision=bf16",
              "--trainer.default_root_dir=/pvc/logs/final_scores/diag/codes/PubMedBERT",
              "--trainer.callbacks=EarlyStopping",
              "--trainer.callbacks.patience=10",
              "--trainer.callbacks.mode=max",
              "--trainer.callbacks.monitor=Val/nDCG@30",
              "--trainer.callbacks=ModelCheckpoint",
              "--trainer.callbacks.dirpath=/pvc/final_scores/diag/codes/PubMedBERT",
              "--trainer.callbacks.filename=checkpoint",
              "--trainer.callbacks.save_top_k=1",
              "--trainer.callbacks.mode=max",
              "--trainer.callbacks.monitor=Val/nDCG@30",
              "--trainer.num_sanity_val_steps=0",
              "--data.num_workers=16",
              "--data.eval_batch_size=128",
              "--data.batch_size=32",
              "--data.tokenizer=microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract",
              "--model.encoder_model_name=microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract",
              "--model.num_classes=280",
              "--model.warmup_steps=150",
              "--model.decay_steps=20000",
              "--model.lr=2e-5",
              "--seed_everything=42",
              "--data.num_codes_to_add=0",
              "--data.num_codes_to_add_val=3",
              "--data.data_dir=/pvc/ClinicalOutcomeDecoder/data/ccs2/coP_full",
              "--data.use_ccs=True",
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
            - name: TOKENIZERS_PARALLELISM
              value: 'true'
            - name: NCCL_DEBUG
              value: 'INFO'
            - name: TRANSFORMERS_CACHE
              value: "/pvc/huggingface_cache"

          resources:
            requests:
              cpu: "1"
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: cod-shared-pvc
              mountPath: /pvc
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: cod-shared-pvc
          persistentVolumeClaim:
            claimName: cod-shared-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
