apiVersion: batch/v1
kind: Job
metadata:
  name: readmissions-codes-classifier
  labels:
    app: readmissions-codes-classifier
spec:
  template:
    metadata:
      labels:
        app: readmissions-codes-classifier
    spec:
      containers:
        - name: clinical-classification
          image: <anonymized>
          command: [
              "python", "classification_main_readmissions.py",
              "fit",
              "--trainer.accelerator=gpu",
              "--trainer.devices=1",
              "--trainer.precision=bf16",
              "--trainer.default_root_dir=/pvc/logs/final_scores/readmissions/codes/PubMedBERT",
              "--trainer.callbacks=EarlyStopping",
              "--trainer.callbacks.patience=10",
              "--trainer.callbacks.mode=max",
              "--trainer.callbacks.monitor=Val/nDCG@30",
              "--trainer.callbacks=ModelCheckpoint",
              "--trainer.callbacks.dirpath=/pvc/final_scores/readmissions/codes/PubMedBERT",
              "--trainer.callbacks.filename=checkpoint",
              "--trainer.callbacks.save_top_k=1",
              "--trainer.callbacks.mode=max",
              "--trainer.callbacks.monitor=Val/nDCG@30",
              "--trainer.num_sanity_val_steps=0",
              "--model.encoder_model_name=microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract",
              "--model.num_classes=270",
              "--model.warmup_steps=500",
              "--model.decay_steps=200000",
              "--model.lr=4e-5",
              "--model.readmission_task=True",
              "--seed_everything=42",
              "--data.num_workers=8",
              "--data.eval_batch_size=128",
              "--data.batch_size=16",
              "--data.code_descriptions=/pvc/icd_desc.txt",
              "--data.umls_text=False",
              "--data.use_text_descriptions=False",
              "--data.use_ccs=True",
              "--data.filename=/pvc/ClinicalOutcomeDecoder/data/mimic3_readmissions_UMLS2021AB.json",
              "--data.admission_notes=/pvc/ClinicalOutcomeDecoder/data/admission_notes.json",
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
            - name: TOKENIZERS_PARALLELISM
              value: 'true'
            - name: PYTHONPATH
              value: "simple_attention_model/"
            - name: NCCL_DEBUG
              value: 'INFO'
            - name: TRANSFORMERS_CACHE
              value: "/pvc/huggingface_cache"
          resources:
            requests:
              cpu: "1"
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: cod-shared-pvc
              mountPath: /pvc
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: cod-shared-pvc
          persistentVolumeClaim:
            claimName: cod-shared-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
